(function() {var implementors = {};
implementors["archive"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"enum\" href=\"archive/enum.Origin.html\" title=\"enum archive::Origin\">Origin</a>",synthetic:false,types:["archive::Origin"]},];
implementors["notion_core"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"notion_core/distro/node/struct.NodeVersion.html\" title=\"struct notion_core::distro::node::NodeVersion\">NodeVersion</a>",synthetic:false,types:["notion_core::distro::node::NodeVersion"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"notion_core/distro/package/struct.PackageDistro.html\" title=\"struct notion_core::distro::package::PackageDistro\">PackageDistro</a>",synthetic:false,types:["notion_core::distro::package::PackageDistro"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"notion_core/distro/package/struct.PackageVersion.html\" title=\"struct notion_core::distro::package::PackageVersion\">PackageVersion</a>",synthetic:false,types:["notion_core::distro::package::PackageVersion"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"notion_core/platform/struct.PlatformSpec.html\" title=\"struct notion_core::platform::PlatformSpec\">PlatformSpec</a>",synthetic:false,types:["notion_core::platform::PlatformSpec"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"notion_core/platform/struct.Image.html\" title=\"struct notion_core::platform::Image\">Image</a>",synthetic:false,types:["notion_core::platform::Image"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"enum\" href=\"notion_core/session/enum.ActivityKind.html\" title=\"enum notion_core::session::ActivityKind\">ActivityKind</a>",synthetic:false,types:["notion_core::session::ActivityKind"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"enum\" href=\"notion_core/version/enum.VersionSpec.html\" title=\"enum notion_core::version::VersionSpec\">VersionSpec</a>",synthetic:false,types:["notion_core::version::VersionSpec"]},];
implementors["notion_fail"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"enum\" href=\"notion_fail/enum.ExitCode.html\" title=\"enum notion_fail::ExitCode\">ExitCode</a>",synthetic:false,types:["notion_fail::ExitCode"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
