(function() {var implementors = {};
implementors["archive"] = [{text:"impl Fail for <a class=\"struct\" href=\"archive/tarball/struct.MissingHeaderError.html\" title=\"struct archive::tarball::MissingHeaderError\">MissingHeaderError</a>",synthetic:false,types:[]},{text:"impl Fail for <a class=\"struct\" href=\"archive/tarball/struct.UnexpectedContentLengthError.html\" title=\"struct archive::tarball::UnexpectedContentLengthError\">UnexpectedContentLengthError</a>",synthetic:false,types:[]},{text:"impl Fail for <a class=\"struct\" href=\"archive/tarball/struct.ByteRangesNotAcceptedError.html\" title=\"struct archive::tarball::ByteRangesNotAcceptedError\">ByteRangesNotAcceptedError</a>",synthetic:false,types:[]},{text:"impl Fail for <a class=\"struct\" href=\"archive/struct.HttpError.html\" title=\"struct archive::HttpError\">HttpError</a>",synthetic:false,types:["archive::HttpError"]},];
implementors["notion_core"] = [{text:"impl Fail for <a class=\"enum\" href=\"notion_core/error/enum.ErrorDetails.html\" title=\"enum notion_core::error::ErrorDetails\">ErrorDetails</a>",synthetic:false,types:["notion_core::error::ErrorDetails"]},{text:"impl Fail for <a class=\"struct\" href=\"notion_core/hook/serial/struct.MultipleFieldsSpecified.html\" title=\"struct notion_core::hook::serial::MultipleFieldsSpecified\">MultipleFieldsSpecified</a>",synthetic:false,types:[]},{text:"impl Fail for <a class=\"struct\" href=\"notion_core/hook/serial/struct.NoFieldSpecified.html\" title=\"struct notion_core::hook::serial::NoFieldSpecified\">NoFieldSpecified</a>",synthetic:false,types:[]},{text:"impl Fail for <a class=\"struct\" href=\"notion_core/hook/serial/struct.BothUrlAndBin.html\" title=\"struct notion_core::hook::serial::BothUrlAndBin\">BothUrlAndBin</a>",synthetic:false,types:[]},{text:"impl Fail for <a class=\"struct\" href=\"notion_core/hook/serial/struct.NeitherUrlNorBin.html\" title=\"struct notion_core::hook::serial::NeitherUrlNorBin\">NeitherUrlNorBin</a>",synthetic:false,types:[]},];
implementors["notion_fail"] = [{text:"impl Fail for <a class=\"struct\" href=\"notion_fail/struct.NotionError.html\" title=\"struct notion_fail::NotionError\">NotionError</a>",synthetic:false,types:["notion_fail::NotionError"]},{text:"impl Fail for <a class=\"struct\" href=\"notion_fail/struct.UnknownNotionError.html\" title=\"struct notion_fail::UnknownNotionError\">UnknownNotionError</a>",synthetic:false,types:[]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
