(function() {var implementors = {};
implementors["archive"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"struct\" href=\"archive/tarball/struct.MissingHeaderError.html\" title=\"struct archive::tarball::MissingHeaderError\">MissingHeaderError</a>",synthetic:false,types:[]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"struct\" href=\"archive/tarball/struct.UnexpectedContentLengthError.html\" title=\"struct archive::tarball::UnexpectedContentLengthError\">UnexpectedContentLengthError</a>",synthetic:false,types:[]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"struct\" href=\"archive/tarball/struct.ByteRangesNotAcceptedError.html\" title=\"struct archive::tarball::ByteRangesNotAcceptedError\">ByteRangesNotAcceptedError</a>",synthetic:false,types:[]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"struct\" href=\"archive/struct.HttpError.html\" title=\"struct archive::HttpError\">HttpError</a>",synthetic:false,types:["archive::HttpError"]},];
implementors["notion_core"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"enum\" href=\"notion_core/error/enum.ErrorDetails.html\" title=\"enum notion_core::error::ErrorDetails\">ErrorDetails</a>",synthetic:false,types:["notion_core::error::ErrorDetails"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"struct\" href=\"notion_core/hook/serial/struct.MultipleFieldsSpecified.html\" title=\"struct notion_core::hook::serial::MultipleFieldsSpecified\">MultipleFieldsSpecified</a>",synthetic:false,types:[]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"struct\" href=\"notion_core/hook/serial/struct.NoFieldSpecified.html\" title=\"struct notion_core::hook::serial::NoFieldSpecified\">NoFieldSpecified</a>",synthetic:false,types:[]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"struct\" href=\"notion_core/hook/serial/struct.BothUrlAndBin.html\" title=\"struct notion_core::hook::serial::BothUrlAndBin\">BothUrlAndBin</a>",synthetic:false,types:[]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"struct\" href=\"notion_core/hook/serial/struct.NeitherUrlNorBin.html\" title=\"struct notion_core::hook::serial::NeitherUrlNorBin\">NeitherUrlNorBin</a>",synthetic:false,types:[]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"enum\" href=\"notion_core/session/enum.ActivityKind.html\" title=\"enum notion_core::session::ActivityKind\">ActivityKind</a>",synthetic:false,types:["notion_core::session::ActivityKind"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"enum\" href=\"notion_core/tool/enum.ToolSpec.html\" title=\"enum notion_core::tool::ToolSpec\">ToolSpec</a>",synthetic:false,types:["notion_core::tool::ToolSpec"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"enum\" href=\"notion_core/version/enum.VersionSpec.html\" title=\"enum notion_core::version::VersionSpec\">VersionSpec</a>",synthetic:false,types:["notion_core::version::VersionSpec"]},];
implementors["notion_fail"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"struct\" href=\"notion_fail/struct.NotionError.html\" title=\"struct notion_fail::NotionError\">NotionError</a>",synthetic:false,types:["notion_fail::NotionError"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"struct\" href=\"notion_fail/struct.UnknownNotionError.html\" title=\"struct notion_fail::UnknownNotionError\">UnknownNotionError</a>",synthetic:false,types:[]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
